-- Analytics layer: raw plant data -> operational signals, entirely in Exasol SQL.
-- The assistant never computes risk; it reads what these views already decided.
-- All windows are relative to the database clock (CURRENT_TIMESTAMP), so answers
-- to "today" / "this week" stay correct whenever the demo runs.
-- Statements separated by a single ';' and applied one at a time by scripts/seed.ts.

-- Per-machine sensor summary over the last 24h.
CREATE OR REPLACE VIEW PLANTOPS.V_MACHINE_SENSORS_24H AS
SELECT
  m.MACHINE_ID,
  ROUND(AVG(s.VIBRATION), 2)   AS AVG_VIBRATION_24H,
  ROUND(MAX(s.VIBRATION), 2)   AS MAX_VIBRATION_24H,
  ROUND(AVG(s.TEMPERATURE), 2) AS AVG_TEMP_24H,
  COUNT(s.READING_ID)          AS READING_COUNT_24H
FROM PLANTOPS.MACHINES m
LEFT JOIN PLANTOPS.SENSOR_READINGS s
  ON s.MACHINE_ID = m.MACHINE_ID
  AND s.TS >= ADD_HOURS(CURRENT_TIMESTAMP, -24)
GROUP BY m.MACHINE_ID;

-- Per-machine error counts over the last 24h (E5xx = severe).
CREATE OR REPLACE VIEW PLANTOPS.V_MACHINE_ERRORS_24H AS
SELECT
  m.MACHINE_ID,
  COUNT(e.ERROR_ID) AS ERROR_COUNT_24H,
  SUM(CASE WHEN e.ERROR_CODE LIKE 'E5%' THEN 1 ELSE 0 END) AS SEVERE_ERROR_COUNT_24H,
  GROUP_CONCAT(DISTINCT e.ERROR_CODE) AS ERROR_CODES_24H
FROM PLANTOPS.MACHINES m
LEFT JOIN PLANTOPS.ERROR_LOGS e
  ON e.MACHINE_ID = m.MACHINE_ID
  AND e.TS >= ADD_HOURS(CURRENT_TIMESTAMP, -24)
GROUP BY m.MACHINE_ID;

-- Per-machine downtime over the last 7 days.
CREATE OR REPLACE VIEW PLANTOPS.V_MACHINE_DOWNTIME_7D AS
SELECT
  m.MACHINE_ID,
  COALESCE(SUM(d.DOWNTIME_MINUTES), 0) AS DOWNTIME_MIN_7D,
  COUNT(d.EVENT_ID)                    AS DOWNTIME_EVENTS_7D
FROM PLANTOPS.MACHINES m
LEFT JOIN PLANTOPS.DOWNTIME_EVENTS d
  ON d.MACHINE_ID = m.MACHINE_ID
  AND d.START_TS >= ADD_DAYS(CURRENT_TIMESTAMP, -7)
GROUP BY m.MACHINE_ID;

-- Most recent maintenance record per machine, with overdue flag.
CREATE OR REPLACE VIEW PLANTOPS.V_MACHINE_MAINTENANCE AS
SELECT
  MACHINE_ID,
  MAINT_DATE    AS LAST_MAINT_DATE,
  NEXT_DUE_DATE,
  CASE WHEN NEXT_DUE_DATE < CURRENT_DATE THEN 1 ELSE 0 END AS MAINT_OVERDUE
FROM (
  SELECT
    r.MACHINE_ID,
    r.MAINT_DATE,
    r.NEXT_DUE_DATE,
    ROW_NUMBER() OVER (PARTITION BY r.MACHINE_ID ORDER BY r.MAINT_DATE DESC) AS RN
  FROM PLANTOPS.MAINTENANCE_RECORDS r
)
WHERE RN = 1;

-- One row per machine: all health signals joined with plant/line context.
CREATE OR REPLACE VIEW PLANTOPS.V_MACHINE_HEALTH AS
SELECT
  m.MACHINE_ID,
  m.MACHINE_NAME,
  m.MACHINE_TYPE,
  l.LINE_ID,
  l.LINE_NAME,
  p.PLANT_ID,
  p.PLANT_NAME,
  m.VIBRATION_BASELINE,
  s.AVG_VIBRATION_24H,
  s.MAX_VIBRATION_24H,
  s.AVG_TEMP_24H,
  s.READING_COUNT_24H,
  CASE
    WHEN m.VIBRATION_BASELINE > 0 AND s.AVG_VIBRATION_24H IS NOT NULL
    THEN ROUND((s.AVG_VIBRATION_24H - m.VIBRATION_BASELINE) / m.VIBRATION_BASELINE * 100, 1)
    ELSE 0
  END AS VIBRATION_PCT_OVER_BASELINE,
  COALESCE(er.ERROR_COUNT_24H, 0)        AS ERROR_COUNT_24H,
  COALESCE(er.SEVERE_ERROR_COUNT_24H, 0) AS SEVERE_ERROR_COUNT_24H,
  er.ERROR_CODES_24H,
  COALESCE(dt.DOWNTIME_MIN_7D, 0)        AS DOWNTIME_MIN_7D,
  COALESCE(dt.DOWNTIME_EVENTS_7D, 0)     AS DOWNTIME_EVENTS_7D,
  mt.LAST_MAINT_DATE,
  mt.NEXT_DUE_DATE,
  COALESCE(mt.MAINT_OVERDUE, 0)          AS MAINT_OVERDUE
FROM PLANTOPS.MACHINES m
JOIN PLANTOPS.PRODUCTION_LINES l ON l.LINE_ID = m.LINE_ID
JOIN PLANTOPS.PLANTS p           ON p.PLANT_ID = l.PLANT_ID
LEFT JOIN PLANTOPS.V_MACHINE_SENSORS_24H s ON s.MACHINE_ID = m.MACHINE_ID
LEFT JOIN PLANTOPS.V_MACHINE_ERRORS_24H er ON er.MACHINE_ID = m.MACHINE_ID
LEFT JOIN PLANTOPS.V_MACHINE_DOWNTIME_7D dt ON dt.MACHINE_ID = m.MACHINE_ID
LEFT JOIN PLANTOPS.V_MACHINE_MAINTENANCE mt ON mt.MACHINE_ID = m.MACHINE_ID;

-- Explainable risk score (0-100) decomposed into named components, plus band
-- and recommended action. This is what powers "why is this machine high risk?".
--   vibration: 0-40  (1 point per % over baseline, capped)
--   errors:    0-30  (severe x8, others x3, capped)
--   downtime:  0-20  (1 point per 15 downtime-minutes in 7d, capped)
--   maintenance:0-10 (overdue = 10)
CREATE OR REPLACE VIEW PLANTOPS.V_RISK_SCORE AS
SELECT
  scored.*,
  CASE
    WHEN RISK_SCORE >= 60 THEN 'HIGH'
    WHEN RISK_SCORE >= 30 THEN 'MEDIUM'
    ELSE 'LOW'
  END AS RISK_BAND,
  CASE
    WHEN RISK_SCORE >= 60 THEN 'Inspect within 24 hours'
    WHEN RISK_SCORE >= 30 THEN 'Schedule inspection this week'
    ELSE 'Monitor'
  END AS RECOMMENDED_ACTION
FROM (
  SELECT
    comp.*,
    (VIBRATION_SCORE + ERROR_SCORE + DOWNTIME_SCORE + MAINTENANCE_SCORE) AS RISK_SCORE
  FROM (
    SELECT
      h.*,
      LEAST(40, GREATEST(0, ROUND(h.VIBRATION_PCT_OVER_BASELINE, 0)))                               AS VIBRATION_SCORE,
      LEAST(30, h.SEVERE_ERROR_COUNT_24H * 8 + (h.ERROR_COUNT_24H - h.SEVERE_ERROR_COUNT_24H) * 3)   AS ERROR_SCORE,
      LEAST(20, ROUND(h.DOWNTIME_MIN_7D / 15.0, 0))                                                  AS DOWNTIME_SCORE,
      CASE WHEN h.MAINT_OVERDUE = 1 THEN 10 ELSE 0 END                                               AS MAINTENANCE_SCORE
    FROM PLANTOPS.V_MACHINE_HEALTH h
  ) comp
) scored;

-- Ranked list of machines that need attention now (HIGH/MEDIUM), with reasons.
CREATE OR REPLACE VIEW PLANTOPS.V_MACHINES_NEEDING_ATTENTION AS
SELECT
  MACHINE_ID,
  MACHINE_NAME,
  MACHINE_TYPE,
  PLANT_NAME,
  LINE_NAME,
  RISK_SCORE,
  RISK_BAND,
  RECOMMENDED_ACTION,
  VIBRATION_PCT_OVER_BASELINE,
  AVG_VIBRATION_24H,
  VIBRATION_BASELINE,
  ERROR_COUNT_24H,
  SEVERE_ERROR_COUNT_24H,
  ERROR_CODES_24H,
  DOWNTIME_MIN_7D,
  MAINT_OVERDUE,
  VIBRATION_SCORE,
  ERROR_SCORE,
  DOWNTIME_SCORE,
  MAINTENANCE_SCORE
FROM PLANTOPS.V_RISK_SCORE
WHERE RISK_BAND IN ('HIGH', 'MEDIUM')
ORDER BY RISK_SCORE DESC;

-- Machines logging the same error code repeatedly (>=3 times) in the last 7 days.
CREATE OR REPLACE VIEW PLANTOPS.V_REPEATED_ERRORS AS
SELECT
  e.MACHINE_ID,
  m.MACHINE_NAME,
  p.PLANT_NAME,
  e.ERROR_CODE,
  MAX(e.SEVERITY)      AS SEVERITY,
  COUNT(*)             AS OCCURRENCES_7D,
  MIN(e.TS)            AS FIRST_SEEN,
  MAX(e.TS)            AS LAST_SEEN,
  MAX(e.DESCRIPTION)   AS DESCRIPTION
FROM PLANTOPS.ERROR_LOGS e
JOIN PLANTOPS.MACHINES m         ON m.MACHINE_ID = e.MACHINE_ID
JOIN PLANTOPS.PRODUCTION_LINES l ON l.LINE_ID = m.LINE_ID
JOIN PLANTOPS.PLANTS p           ON p.PLANT_ID = l.PLANT_ID
WHERE e.TS >= ADD_DAYS(CURRENT_TIMESTAMP, -7)
GROUP BY e.MACHINE_ID, m.MACHINE_NAME, p.PLANT_NAME, e.ERROR_CODE
HAVING COUNT(*) >= 3
ORDER BY OCCURRENCES_7D DESC;

-- Plant downtime over the last 7 days ("which plant has the most downtime this week").
CREATE OR REPLACE VIEW PLANTOPS.V_PLANT_DOWNTIME_7D AS
SELECT
  p.PLANT_ID,
  p.PLANT_NAME,
  COALESCE(SUM(d.DOWNTIME_MINUTES), 0) AS DOWNTIME_MIN_7D,
  COUNT(d.EVENT_ID)                    AS DOWNTIME_EVENTS_7D
FROM PLANTOPS.PLANTS p
LEFT JOIN PLANTOPS.PRODUCTION_LINES l ON l.PLANT_ID = p.PLANT_ID
LEFT JOIN PLANTOPS.MACHINES m         ON m.LINE_ID = l.LINE_ID
LEFT JOIN PLANTOPS.DOWNTIME_EVENTS d
  ON d.MACHINE_ID = m.MACHINE_ID
  AND d.START_TS >= ADD_DAYS(CURRENT_TIMESTAMP, -7)
GROUP BY p.PLANT_ID, p.PLANT_NAME
ORDER BY DOWNTIME_MIN_7D DESC;

-- Daily downtime per plant over the last 14 days (trend sparkline source).
CREATE OR REPLACE VIEW PLANTOPS.V_DOWNTIME_TRENDS AS
SELECT
  p.PLANT_ID,
  p.PLANT_NAME,
  TO_CHAR(d.START_TS, 'YYYY-MM-DD') AS DAY_LABEL,
  SUM(d.DOWNTIME_MINUTES)           AS DOWNTIME_MIN,
  COUNT(*)                          AS EVENTS
FROM PLANTOPS.DOWNTIME_EVENTS d
JOIN PLANTOPS.MACHINES m         ON m.MACHINE_ID = d.MACHINE_ID
JOIN PLANTOPS.PRODUCTION_LINES l ON l.LINE_ID = m.LINE_ID
JOIN PLANTOPS.PLANTS p           ON p.PLANT_ID = l.PLANT_ID
WHERE d.START_TS >= ADD_DAYS(CURRENT_TIMESTAMP, -14)
GROUP BY p.PLANT_ID, p.PLANT_NAME, TO_CHAR(d.START_TS, 'YYYY-MM-DD')
ORDER BY p.PLANT_ID, DAY_LABEL;

-- Plant-level health rollup.
CREATE OR REPLACE VIEW PLANTOPS.V_PLANT_HEALTH AS
SELECT
  r.PLANT_ID,
  r.PLANT_NAME,
  COUNT(*)                                                  AS MACHINE_COUNT,
  SUM(CASE WHEN r.RISK_BAND = 'HIGH' THEN 1 ELSE 0 END)     AS HIGH_RISK_COUNT,
  SUM(CASE WHEN r.RISK_BAND = 'MEDIUM' THEN 1 ELSE 0 END)   AS MEDIUM_RISK_COUNT,
  ROUND(AVG(r.RISK_SCORE), 1)                               AS AVG_RISK_SCORE,
  COALESCE(MAX(pd.DOWNTIME_MIN_7D), 0)                      AS DOWNTIME_MIN_7D
FROM PLANTOPS.V_RISK_SCORE r
LEFT JOIN PLANTOPS.V_PLANT_DOWNTIME_7D pd ON pd.PLANT_ID = r.PLANT_ID
GROUP BY r.PLANT_ID, r.PLANT_NAME
ORDER BY AVG_RISK_SCORE DESC;

-- Maintenance priority: risk plus an overdue boost.
CREATE OR REPLACE VIEW PLANTOPS.V_MAINTENANCE_PRIORITY AS
SELECT
  MACHINE_ID,
  MACHINE_NAME,
  PLANT_NAME,
  LINE_NAME,
  RISK_SCORE,
  RISK_BAND,
  NEXT_DUE_DATE,
  MAINT_OVERDUE,
  RECOMMENDED_ACTION,
  (RISK_SCORE + CASE WHEN MAINT_OVERDUE = 1 THEN 25 ELSE 0 END) AS PRIORITY_SCORE
FROM PLANTOPS.V_RISK_SCORE
ORDER BY PRIORITY_SCORE DESC;
